####################################################################################################
############################## Сервис пользователей #################################################
####################################################################################################
@userId={{login.response.body.user.id}}
@email={{login.response.body.user.email}}
@AToken={{login.response.body.token}}



# Регистрация нового пользователя
# @name register
POST http://localhost:4000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "birthday": "1999-01-21 16:44:55.512",
  "email": "keks@notfound.local",
  "password": "123456",
  "role": "admin",
  "status":"active"
}

###

# Аутентификация пользователя
# @name login
POST http://localhost:4000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks@notfound.local",
  "password": "123456"
}

###

# Получение всех пользователей
GET http://localhost:4000/api/users HTTP/1.1
Authorization: Bearer {{AToken}}

###

# Получение информации о пользователе по ID
GET http://localhost:4000/api/users/{{userId}} HTTP/1.1
Authorization: Bearer {{AToken}}


###


# Блокировка пользователя
PUT  http://localhost:4000/api/users/085a1889-4c9a-479b-af94-76cd23c81a73 HTTP/1.1
Authorization: Bearer {{AToken}}