####################################################################################################
############################## Сервис пользователей #################################################
####################################################################################################
@userId={{login.response.body.id}}
@email={{login.response.body.email}}
@AToken={{login.response.body.accessToken}}



# Создание нового пользователя
# @name create
POST http://localhost:4000/api/users HTTP/1.1
Content-Type: application/json

{
  "name": "John",
  "email": "kek01@notfound.local",
  "password": "123456",
  "role": "admin",
  "status":"active"
}

###

# Обновление пользователя
# @name update
PUT http://localhost:4000/api/users/0dcf95fe-3b48-430a-bebe-ff034810d5b3 HTTP/1.1
Content-Type: application/json

{
  "email": "kek01@notfound.local",
  "status":"Not Active"
}

###

# Получение всех пользователей
GET http://localhost:4000/api/users HTTP/1.1

###

# Получение информации о пользователе по ID
GET http://localhost:4000/api/users/b4a99267-9f45-4c75-974f-588fc17c6228 HTTP/1.1

###

# Удаление пользователя
DELETE  http://localhost:4000/api/users/b4a99267-9f45-4c75-974f-588fc17c6228 HTTP/1.1

###

# Аутентификация пользователя
# @name login
POST http://localhost:4000/guitar/auth-user/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks@gmail.com",
  "password": "123123"
}

###

# Проверка пользователя по токену
GET http://localhost:4000/guitar/auth-user/validate/{{AToken}} HTTP/1.1
Authorization: Bearer {{AToken}}

